package com.wyona.katie.models.insights;

public enum EventType {

    GET_FAQ,
    MESSAGE_RECEIVED,
    QUESTION_SENT_TO_EXPERT,
    FEEDBACK_10,
    FEEDBACK_1,
    FEEDBACK_PREDICTED_LABEL_POSITIVE,
    FEEDBACK_PREDICTED_LABEL_NEGATIVE,
    ASKED_QUESTION,
    ANSWERED_QUESTION,
    NEXT_BEST_ANSWER
}
