FROM openjdk:11
#https://hub.docker.com/_/openjdk
#https://hub.docker.com/_/tomcat
#https://www.middlewareinventory.com/blog/docker-tomcat-example-dockerfile-sample/
#https://spring.io/blog/2018/11/08/spring-boot-in-a-container
MAINTAINER katie.qa

VOLUME /tmp

# TLS 1.0 and 1.1 enabled in order to be able to connect to IMAP servers which do not support more recent protocols, whereas see jdk.tls.disabledAlgorithms
COPY java.security /usr/local/openjdk-11/conf/security/.

RUN mkdir /opt/tomcat/
WORKDIR /opt/tomcat
RUN curl -O https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.100/bin/apache-tomcat-8.5.100.tar.gz
#RUN curl -O https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.56/bin/apache-tomcat-9.0.56.tar.gz
RUN tar xvfz apache*.tar.gz
RUN mv apache-tomcat-8.5.100/* /opt/tomcat/.
#RUN mv apache-tomcat-9.0.56/* /opt/tomcat/.
RUN chmod -R 775 /opt/tomcat

COPY target/askkatie-webapp-*.war /opt/tomcat/webapps/katie.war
#COPY target/askkatie-webapp-*.war /opt/tomcat/webapps/.
#RUN rm -rf /opt/tomcat/webapps/ROOT
#COPY target/askkatie-webapp-*.war /opt/tomcat/webapps/ROOT.war

EXPOSE 8080
CMD ["/opt/tomcat/bin/catalina.sh", "run"]
