package com.wyona.katie.handlers;

import com.wyona.katie.models.*;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.azure.openai.AzureOpenAiChatModel;
import org.springframework.ai.azure.openai.AzureOpenAiChatOptions;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.List;

import com.azure.ai.openai.OpenAIClientBuilder;
import com.azure.core.credential.AzureKeyCredential;

/**
 *
 */
@Slf4j
@Component
public class AzureGenerate implements GenerateProvider {

    // Uses spring.ai.azure.openai.endpoint and spring.ai.azure.openai.api-key
    //@Autowired
    //AzureOpenAiChatModel azureOpenAiChatModel;

    /**
     * @see GenerateProvider#getAssistant(String, String, String, List, CompletionConfig)
     */
    public CompletionAssistant getAssistant(String id, String name, String instructions, List<CompletionTool> tools, CompletionConfig completionConfig) throws Exception {
        log.error("Not implemented yet!");
        return null;
    }

    /**
     * @see GenerateProvider#getCompletion(List, CompletionAssistant, CompletionConfig, Double)
     */
    public CompletionResponse getCompletion(List<PromptMessage> promptMessages, CompletionAssistant assistant, CompletionConfig completionConfig, Double temperature) throws Exception {
        return getCompletionUsingSpringAI(promptMessages, assistant, completionConfig, temperature);
    }

    /**
     * Get completion using Spring AI implementation
     */
    private CompletionResponse getCompletionUsingSpringAI(List<PromptMessage> promptMessages, CompletionAssistant assistant, CompletionConfig completionConfig, Double temperature) throws Exception {
        log.info("Spring AI Azure OpenAI implementation (Deployment / Model: " + completionConfig.getModel() + ") ...");
        PromptMessage firstMessage = promptMessages.get(0);

        AzureOpenAiChatOptions options = AzureOpenAiChatOptions.builder()
                .deploymentName(completionConfig.getModel())
                .temperature(temperature)
                .build();

        OpenAIClientBuilder openAIClientBuilder = new OpenAIClientBuilder()
                .credential(new AzureKeyCredential(completionConfig.getApiKey()))
                .endpoint(completionConfig.getHost());
        log.info("Endpoint: " + completionConfig.getHost());

        AzureOpenAiChatModel azureOpenAiChatModel =
                AzureOpenAiChatModel.builder()
                        .openAIClientBuilder(openAIClientBuilder)
                        .build();

        ChatResponse response = azureOpenAiChatModel.call(
                new Prompt(
                        firstMessage.getContent(),
                        options
                )
        );

        log.info("Completion generated by model: " + response.getMetadata().getModel());

        return new CompletionResponse(response.getResult().toString());
    }
}
