package com.wyona.katie.handlers;

import com.wyona.katie.models.*;
import lombok.extern.slf4j.Slf4j;
import org.springframework.ai.azure.openai.AzureOpenAiChatModel;
import org.springframework.ai.azure.openai.AzureOpenAiChatOptions;
import org.springframework.ai.chat.model.ChatResponse;
import org.springframework.ai.chat.prompt.Prompt;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 *
 */
@Slf4j
@Component
public class AzureGenerate implements GenerateProvider {

    @Autowired
    AzureOpenAiChatModel azureOpenAiChatModel;

    /**
     * @see GenerateProvider#getAssistant(String, String, String, List, CompletionConfig)
     */
    public CompletionAssistant getAssistant(String id, String name, String instructions, List<CompletionTool> tools, CompletionConfig completionConfig) throws Exception {
        log.error("Not implemented yet!");
        return null;
    }

    /**
     * @see GenerateProvider#getCompletion(List, CompletionAssistant, CompletionConfig, Double)
     */
    public CompletionResponse getCompletion(List<PromptMessage> promptMessages, CompletionAssistant assistant, CompletionConfig completionConfig, Double temperature) throws Exception {
        return getCompletionUsingSpringAI(promptMessages, assistant, completionConfig, temperature);
    }

    /**
     * Get completion using Spring AI implementation
     */
    private CompletionResponse getCompletionUsingSpringAI(List<PromptMessage> promptMessages, CompletionAssistant assistant, CompletionConfig completionConfig, Double temperature) throws Exception {
        log.info("Spring AI Azure OpenAI implementation (Deployment / Model: " + completionConfig.getModel() + ") ...");
        PromptMessage firstMessage = promptMessages.get(0);

        // TODO: Set host and API key from domain config, because otherwise spring.ai.azure.openai.endpoint and spring.ai.azure.openai.api-key will be used
        completionConfig.getHost();
        completionConfig.getApiKey();
        AzureOpenAiChatOptions options = AzureOpenAiChatOptions.builder()
                .deploymentName(completionConfig.getModel())
                .temperature(temperature)
                .build();

        ChatResponse response = azureOpenAiChatModel.call(
                new Prompt(
                        firstMessage.getContent(),
                        options
                )
        );

        log.info("Completion generated by model: " + response.getMetadata().getModel());

        return new CompletionResponse(response.getResult().toString());
    }
}
