-- add new columns USER_NAME, ANSWER_UUID, PERMISSION_STATUS, MODERATION_STATUS (NEEDS_APPROVAL, APPROVED)
ALTER TABLE QUESTION add USER_NAME varchar(100);
ALTER TABLE QUESTION add ANSWER_UUID varchar(100);
ALTER TABLE QUESTION add PERMISSION_STATUS varchar(100);
ALTER TABLE QUESTION add MODERATION_STATUS varchar(100);
